/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectobdotomasgonzalez;

import com.db4o.Db4o;
import com.db4o.Db4oEmbedded;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import java.io.File;
import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;
import java.util.Comparator;
import com.db4o.Db4oEmbedded;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet; //consultas
import com.db4o.query.Constraint;//establecer restricciones
import com.db4o.query.Query; //consultas SODA
import java.util.List;
import javax.swing.JOptionPane;

;

/**
 *
 * @author usuario
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("0. Generar autores y libros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("1. Consulta Autores mostrando 4 campos ordenados por tipo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("3. Consulta todos autores de España");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("4. Pedir dos precios y consultar libros de España");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("5. Aumenta los precios de los libros en un 5%. ");

        jButton7.setText("6. Pedir un título de libro y borrar un libro, comprobar que se ha borrado el libro. ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("2. Pedir autor y mostrar todos los libros de ese autor");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton5.setText("Añadir Autor");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton9.setText("Añadir Libro");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Listar todos los libros");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4)))
                        .addGap(0, 136, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            /*File f = new File("bdd.o4bd");
            if (f.exists()) {
                f.delete();
            }*/
            ObjectContainer bd = Db4oEmbedded.openFile("bdd.o4bd");
            Tabla tabla = new Tabla(this, true, 5, bd, "");
            tabla.show();
        } catch (Exception es) {

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //String titulo, String editorial, String tipo, double precio
        Libro l1 = new Libro("La rosa", "Editorial del sur", "ficción", 20);
        Libro l2 = new Libro("La rosa segunda parte", "Editorial del sur", "ficción", 20);
        Libro l3 = new Libro("Las Torres", "Editorial del sur", "Ensayo", 20);
        Libro l4 = new Libro("Las buenas costumbres", "Espasa", "Ensayo", 40);
        //String nombre, String nacionalidad, String tipo, Date fechaNacimiento
        Autor a1 = new Autor("Jose Alcántara", "España", "Ensayista", LocalDate.of(1972, Month.MAY, 23));
        Autor a2 = new Autor("Tom", "España", "Ensayista", LocalDate.of(1972, Month.MAY, 23));
        Autor a3 = new Autor("Francisco", "España", "Ensayista", LocalDate.of(1972, Month.MAY, 23));
        //Autor anon1 = new Autor("España", "Ensayista");
        try {
            File f = new File("bdd.o4bd");
            if (f.exists()) {
                f.delete();
            }
            ObjectContainer bd = Db4oEmbedded.openFile("bdd.o4bd");
            bd.store(l1);
            bd.store(l2);
            bd.store(l3);
            bd.store(l4);
            bd.store(a1);
            bd.store(a2);
            bd.store(a3);
            //bd.store(anon1);
            bd.commit();
            bd.close();
            JOptionPane.showMessageDialog(null, "Borrados todos los datos y he puesto los nuevos");

        } catch (Exception ex) {
            System.out.println("Error");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        /* Autor a = new Autor();
        try {
            File f = new File("bdd.o4bd");
            if (f.exists()) {
                f.delete();
            }
            ObjectContainer bd = Db4oEmbedded.openFile("bdd.o4bd");
            
            ObjectSet<Autor> au = bd.queryByExample(a);
            ArrayList<Autor> arr = new ArrayList<Autor>();
            while (au.hasNext()) {
                arr.add(au.next());
            }
            arr.sort(new Comparator<Autor>() {
                @Override
                public int compare(Autor o1, Autor o2) {
                    int resultado = ("" + o1.getTipo()).compareTo("" + o2.getTipo());
                    if (resultado != 0) {
                        return resultado;
                    } else {
                        return o2.getTipo().compareTo(o1.getTipo());
                    }
                }
            });
        } catch (Exception ex) {
            System.out.println("Error");
            
        }*/
        try {
            /*File f = new File("bdd.o4bd");
            if (f.exists()) {
                f.delete();
            }*/
            ObjectContainer bd = Db4oEmbedded.openFile("bdd.o4bd");
            Tabla tabla = new Tabla(this, true, 1, bd, "");
            tabla.show();
        } catch (Exception es) {

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String name = JOptionPane.showInputDialog("Dígame el nombre del autor");
        //JOptionPane.showMessageDialog(null, "Hello " + name);
        try {
            /*File f = new File("bdd.o4bd");
            if (f.exists()) {
                f.delete();
            }*/
            if (!name.equals("")&&name!=null){
            ObjectContainer bd = Db4oEmbedded.openFile("bdd.o4bd");
            Tabla tabla = new Tabla(this, true, 2, bd, name);
            tabla.show();
            }
        } catch (Exception es) {
            System.out.println("Hola");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String minimo = JOptionPane.showInputDialog("Dígame el precio mínimo");
        String maximo = JOptionPane.showInputDialog("Dígame el precio máximo");
        String name = minimo + " " + maximo;
        //JOptionPane.showMessageDialog(null, "Hello " + name);
        try {
            /*File f = new File("bdd.o4bd");
            if (f.exists()) {
                f.delete();
            }*/
            ObjectContainer bd = Db4oEmbedded.openFile("bdd.o4bd");
            Tabla tabla = new Tabla(this, true, 3, bd, name);
            tabla.show();
        } catch (Exception es) {
            System.out.println("Hola");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        AnydirAutor anydirAutor = new AnydirAutor(this, true);
        anydirAutor.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        AnyadirLibro anyadirLibro = new AnyadirLibro(this, true);        // TODO add your handling code here:
        anyadirLibro.show();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            String tit = JOptionPane.showInputDialog("Dígame el nombre del libro");
            ObjectContainer db = Db4oEmbedded.openFile("bdd.o4bd");
            Query query = db.query(); //declaración de un objeto query(). 
            query.constrain(Libro.class);//establece la clase a la que se aplicará la restricción
            query.descend("titulo").constrain(tit);//establece la restricción de búsqueda
            ObjectSet resul = query.execute();//ejecuta consulta con restricción búsqueda
            while (resul.hasNext()) { //bucle que recupera los objetos charla y elimina de la BDOO
                Libro c = (Libro) resul.next();
                JOptionPane.showMessageDialog(this,"Eliminando: " + c.getTitulo());
                db.delete(c);
            }
            db.close();
            
        } catch (Exception ex) {

        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        //listar libros
        try {
            /*File f = new File("bdd.o4bd");
            if (f.exists()) {
                f.delete();
            }*/
            ObjectContainer bd = Db4oEmbedded.openFile("bdd.o4bd");
            Tabla tabla = new Tabla(this, true, 7, bd, "");
            tabla.show();
        } catch (Exception es) {

        }
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables

}
